version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "Asia/Seoul"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "Asia/Seoul"
    groups:
      actions-dependencies:
        patterns:
          - "*"