name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
      - develop
      - github-actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Adjust if needed, check your project's pnpm version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust if needed, align with your project's Node version
          cache: 'pnpm'

      - name: Install dependencies on GitHub runner
        run: pnpm install

      - name: Determine Deployment Path
        id: set_path
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_PATH=/home/hannal/blink/blinkit-fe" >> $GITHUB_ENV
            echo "Deploying main branch to /home/hannal/blink/blinkit-fe"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_PATH=/home/hannal/blink/blinkit-fe-dev" >> $GITHUB_ENV
            echo "Deploying develop branch to /home/hannal/blink/blinkit-fe-dev"
          elif [[ "${{ github.ref }}" == "refs/heads/github-actions" ]]; then
            echo "DEPLOY_PATH=/home/hannal/blink/blinkit-fe-dev" >> $GITHUB_ENV
            echo "Deploying github-actions branch to /home/hannal/blink/blinkit-fe-dev"
          else
            echo "Branch ${{ github.ref }} is not main, develop, or github-actions. Skipping deployment."
            exit 1 # Exit if not a deployable branch
          fi

      # Create a tar file of the source code (excluding node_modules and .git)
      - name: Create source code archive
        run: |
          tar --exclude='.git' --exclude='node_modules' -czf blinkit-fe-source.tar.gz .
          ls -la blinkit-fe-source.tar.gz
          echo "Created archive of source code"

      # Deploy the files using scp
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BLINKIT_SERVER_HOST }}
          username: hannal
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22022
          source: "blinkit-fe-source.tar.gz"
          target: "/tmp/"

      # Extract the files and install/build on the server
      - name: Setup and Build on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BLINKIT_SERVER_HOST }}
          username: hannal
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22022
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.
            echo "Starting deployment to ${{ env.DEPLOY_PATH }}"
            
            # Ensure target directory exists
            mkdir -p ${{ env.DEPLOY_PATH }}
            
            # Extract the source code archive to the deployment path
            tar -xzf /tmp/blinkit-fe-source.tar.gz -C ${{ env.DEPLOY_PATH }}
            echo "Source code extracted to ${{ env.DEPLOY_PATH }}"
            
            # Change to the deployment directory
            cd ${{ env.DEPLOY_PATH }}
            echo "Current directory: $(pwd)"
            
            # Install dependencies and build
            echo "Running pnpm install..."
            pnpm install
            echo "Running pnpm build..."
            pnpm build
            
            # Clean up
            rm /tmp/blinkit-fe-source.tar.gz
            
            echo "Deployment completed successfully!"
